In [2]:
from random import shuffle 
import numpy as np 

class_nums = [1,2,4,5, ' ']
keytofinger = {'a': class_nums[0], 'b': class_nums[0], 'c': class_nums[0], 'd': class_nums[0], 'e': class_nums[0], 'f': class_nums[0], 'g': class_nums[0],
                    'h': class_nums[1], 'i': class_nums[1], 'j': class_nums[1], 'k': class_nums[1], 'l': class_nums[1], 'm': class_nums[1], 'n': class_nums[1], 'o': class_nums[1],
                    'p': class_nums[2], 'q': class_nums[2], 'r': class_nums[2], 's': class_nums[2], 't': class_nums[2], ',' : class_nums[2],
                    'u': class_nums[3], 'v': class_nums[3], 'w': class_nums[3], 'x': class_nums[3], 'y': class_nums[3], 'z': class_nums[3], '.': class_nums[3],
                    ' ': class_nums[4]
            }
phrase_corpus = open("phrases2.txt").read().splitlines()
def key_distribution(sentence):
    histogram = [0,0,0,0,0,0]
    
    keytofinger = {'a': class_nums[0], 'b': class_nums[0], 'c': class_nums[0], 'd': class_nums[0], 'e': class_nums[0], 'f': class_nums[0], 'g': class_nums[0],
                    'h': class_nums[1], 'i': class_nums[1], 'j': class_nums[1], 'k': class_nums[1], 'l': class_nums[1], 'm': class_nums[1], 'n': class_nums[1], 'o': class_nums[1],
                    'p': class_nums[2], 'q': class_nums[2], 'r': class_nums[2], 's': class_nums[2], 't': class_nums[2], ',' : class_nums[2],
                    'u': class_nums[3], 'v': class_nums[3], 'w': class_nums[3], 'x': class_nums[3], 'y': class_nums[3], 'z': class_nums[3], '.': class_nums[3],
                    ' ': class_nums[4]
            }
    num_text = ""

    sentence = sentence.lower()
    
    for i in sentence:
        if isinstance(keytofinger[i], int): 
            histogram[keytofinger[i]] = histogram[keytofinger[i]]+1
    histogram = np.array(histogram)
    return histogram

In [54]:
sentence_num = 3

In [55]:
# day1_indices = [i for i in range(10)]
max_len_indices = [2, 14, 16, 18, 27, 53, 63, 66, 72, 99]

In [56]:
#### for sentence_num in range(8):

text = phrase_corpus[max_len_indices[sentence_num]].lower()
print(text)
num_text = ""

for i in text:
    num_text += str(keytofinger[i])

print(num_text+' PRESS_SPACE_TO_END')
print(len(num_text), ' characters')
print(key_distribution(text)[1:], ' key distribution')


please provide your date of birth
421141 4425211 5254 1141 21 12442 PRESS_SPACE_TO_END
33  characters
[10  7  0  8  3]  key distribution


#### Online Recalibration Text Generation 

In [165]:
# generating a random offline recalibration string 

char_num = 60
print('There will be ', char_num*5, ' characters in this recalibration experiment.')
# randomize fingers
recal_string = list("1245")*char_num
shuffle(recal_string)
# add spaces but make sure not contiguous
space_indices = np.sort(np.random.choice(np.arange(1,3*char_num-1), char_num, False))
space_indices = space_indices+np.arange(char_num)
space_indices = np.flip(space_indices)
for i in space_indices: 
    recal_string.insert(i, ' ')
print(''.join(recal_string))



There will be  300  characters in this recalibration experiment.
1412255 25 125 4511222 244254 55541 51552 2142225 54 411455 44425 55 52 41155 244 415411125 12 14 51 4425 455151114121422515 24 224215112542 22 52 22 254 2545 1154 52 412 55 14 54552 1225 22411 2541 44 154512 42 4152 55514 151 2441 4441 541 21125 11 4441 2124 24 2122 44 42 512 55 425 11 51 44 141214


In [43]:
for sentence_num in range(500): 
    sentence = phrase_corpus[sentence_num]
    if sentence_num == 0: 
        histogram = key_distribution(sentence)
    else:
        histogram = histogram + key_distribution(sentence)
print(histogram)

[   0 3901 4123    0 2946 1129]


In [42]:
thing = np.array([1,2])
thing + thing

array([2, 4])

In [40]:
strings_8_26 = ["my watch fell in the water"
,"prevailing wind from the east"
,"never too rich and never too thin"
,"I can see the rings on Saturn"
,"physics and chemistry are hard"]

for string in strings_8_26: 
    print(len(string))

26
29
33
29
30
